In [26]:
import pickle
import numpy as np
import itertools
import pandas as pd

In [2]:
upperLeftMatrix = pickle.load(open("./output/matrix/upperleft.out", "rb"))

result = upperLeftMatrix
for j in range(result.shape[0]):
    a = result[j]
    for i in range(a.shape[0]):
        a[i][-1*i:]=np.nan

print(list(result[0][53]))

In [14]:
np.savetxt("./output/matrix/upperleft.csv", upperLeftMatrix[0], delimiter=",")

In [24]:
len(result)

89

In [36]:
OUTPUT_DIR = "./output"
from os import listdir
from os.path import isfile, join
fileLists = [f for f in listdir(OUTPUT_DIR) if f[-4:]==".out"]

In [29]:
stdAvg_dictList = []
for j, tmpMatrix in enumerate(upperLeftMatrix):
    std = np.nanstd(tmpMatrix[0])
    mean = np.nanmean(tmpMatrix[0])
    i = 0
    while np.isnan(std) or np.isnan(mean):
        i+=1
        std = np.nanstd(tmpMatrix[i])
        mean = np.nanmean(tmpMatrix[i])
    stdAvg_dictList.append({"Name": fileLists[j], "Std": std, "Mean": mean})
    print(i, fileLists[j], std, mean)

/Users/lzcai/anaconda3/lib/python3.6/site-packages/numpy/lib/nanfunctions.py:1666: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
/Users/lzcai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.
/Users/lzcai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: Mean of empty slice
  if __name__ == '__main__':

4 ADX General_returnMatrix.out 0.38157628848175945 1.4647527633366382
1 AEX_returnMatrix.out 0.3455271455795936 1.5485632509052007
3 Al-Quds_returnMatrix.out 0.08160189146649238 1.2042161893463146
3 Amman SE General_returnMatrix.out 0.0803185700810113 0.7797850493289584
1747 Athens General Composite_returnMatrix.out 0.19716420623779243 0.7193252150707149
2272 ATX_returnMatrix.out 0.18656998228241223 1.1103342760183479
508 Bahrain All Share_returnMatrix.out 0.08291796346722446 0.8610306424251024
1 BEL 20_returnMatrix.out 0.3252116517737082 1.5094340810546805
1453 Belex 15_returnMatrix.out 0.1510406090285203 1.2718487306448272
1453 BIRS_returnMatrix.out 0.10726466476195551 0.777245791955044
1 BIST 100_returnMatrix.out 0.723249490696876 2.7157276313027863
4 Blue-Chip SBITOP_returnMatrix.out 0.14888585949651353 0.9047527589768981
1 Bovespa_returnMatrix.out 0.2691153210521693 1.4874955103273626
1888 BRVM Composite_returnMatrix.out 0.14392150620071592 1.0562207501504408
4 BSE Domestic Company_returnMatrix.out 0.17917161586091296 1.192451795428797
957 BSE SOFIX_returnMatrix.out 0.32071793266343995 1.3154477573015633
795 Budapest SE_returnMatrix.out 0.3399282744342838 1.0734055090080856
1072 Bursatil_returnMatrix.out 717.3348251157335 281.619007185776
1 CAC 40_returnMatrix.out 0.21823745743320608 1.25450853637762
1 Costa Rica Indice Accionario_returnMatrix.out 0.5261889963759432 1.3195646332303148
4 CROBEX_returnMatrix.out 0.09788130140707087 1.0484652315586314
1 CSE All-Share_returnMatrix.out 0.889279594250744 3.7026411488714834
953 Cyprus Main Market_returnMatrix.out 0.17878490227531763 0.19818705250604285
1 DAX_returnMatrix.out 0.5150314772940919 1.7731100201553334
1490 Dhaka Stock Exchange 30_returnMatrix.out 0.15839500620773025 1.2132707378616252
1 Dow Jones Industrial Average_returnMatrix.out 0.5344064178794651 1.7550099400717893
957 Ecuador Reinvestment_returnMatrix.out 0.14235302218424778 1.2322319290216164
3 EGX 30_returnMatrix.out 0.7474054232069913 1.729989588387498
1 FTSE 100_returnMatrix.out 0.194001842496183 1.3684626461067781
1 FTSE Colombia_returnMatrix.out 0.2866170263498046 1.7890269750302097
504 FTSE Malaysia KLCI_returnMatrix.out 0.1023511358265203 1.2888933648721836
1 FTSE MIB_returnMatrix.out 0.13927286948533424 0.9759459237822822
1747 FTSE NSX Overall_returnMatrix.out 0.13399842224862557 1.12293663108363
795 FTSE Straits Times Singapore_returnMatrix.out 0.07418110242333999 1.0181119520796016
1 FTSE_JSE Top 40_returnMatrix.out 0.5146464575082448 1.9125829289306144
1 Hang Seng_returnMatrix.out 0.23171666059019658 1.5154295122722177
2133 HNX 30_returnMatrix.out 0.17291606305464627 0.982929085915698
1 IBEX 35_returnMatrix.out 0.12716829264380106 1.0115230456191993
1 ICEX Main_returnMatrix.out 0.5482224298715854 1.531796005647545
1030 ISEQ Overall_returnMatrix.out 0.49729664600562085 1.9369928665235017
1903 ISX Main 60_returnMatrix.out 0.1829963999811043 0.7316908003895851
4 Jakarta Stock Exchange Composite Index_returnMatrix.out 0.8399639107526573 3.0692309106906146
2042 JSE Market_returnMatrix.out 1.271813456346914 2.7503655210270352
1 Karachi 100_returnMatrix.out 2.3461358566221415 4.369094784655774
2063 KASE_returnMatrix.out 0.4544022150075182 1.146020766304272
1 Kenya NSE 20_returnMatrix.out 0.20229246879629487 1.1031110951299072
1 KOSPI_returnMatrix.out 0.23240722277707337 1.6985941959503075
1285 LSE All Share_returnMatrix.out 0.19660997201682923 1.3070492678740004
10 MOEX Russia_returnMatrix.out 0.5845490624732509 2.5778740373727
2723 MONEX_returnMatrix.out 0.042599589121597926 1.0336449782495578
1 Moroccan All Shares_returnMatrix.out 0.1187313228921973 1.0100278825521984
3 MSM 30_returnMatrix.out 0.12720095830679454 1.0346092202084751
1 Nasdaq 100_returnMatrix.out 1.3336086226183845 2.929792365971024
1 NASDAQ Composite_returnMatrix.out 1.0540129973741228 2.532587314268737
1 Nifty 50_returnMatrix.out 0.6853746665214935 2.3055348082518186
4 Nikkei 225_returnMatrix.out 0.536339695472714 1.616947857696888
1124 NSE All Share_returnMatrix.out 0.30139057439135813 1.5556796089782847
4 NZX 50_returnMatrix.out 0.7119048292665912 1.8899937601782555
1 OMX Copenhagen 20_returnMatrix.out 1.003282972449342 2.561228689127295
1 OMX Helsinki 25_returnMatrix.out 0.5000995367473339 1.782629974451604
1 OMX Stockholm 30_returnMatrix.out 0.3871114338982037 1.8253637180412643
1062 Oslo All Share_returnMatrix.out 0.38277383349092753 1.6143802730377272
7 PFTS_returnMatrix.out 0.7249438292358398 1.504020902807947
1036 PHS All Shares_returnMatrix.out 0.16651456002796852 1.4186481099278538
509 PSI 20_returnMatrix.out 0.14428538983138722 0.8716957479023456
1111 PX_returnMatrix.out 0.07701438593114333 1.107073101070333
3 QE General_returnMatrix.out 0.2737305104674865 1.343755675066125
1 S&P 500_returnMatrix.out 0.6066708179766601 1.8950046297386363
1 S&P CLX IPSA_returnMatrix.out 0.279860718340263 1.7280562979490959
956 S&P Lima General_returnMatrix.out 0.16970169132426421 0.8417509815356057
1 S&P Merval_returnMatrix.out 8.251036355544429 8.771886878741448
1 S&P Midcap 400_returnMatrix.out 0.7515410540093175 2.264816704992138
1 S&P_ASX 200_returnMatrix.out 0.1792023238630648 1.3632162344533363
1 S&P_BMV IPC_returnMatrix.out 0.3085703260424114 1.740113383131994
1 S&P_TSX Composite_returnMatrix.out 0.19416787784687514 1.45489365820311
956 SAX_returnMatrix.out 0.2542115559401899 1.1393053374649795
4 Semdex_returnMatrix.out 0.2151423945084919 1.60157678150957
4 SET Index_returnMatrix.out 0.7353997597986501 2.6791907233847567
4 Shanghai Composite_returnMatrix.out 0.2891528666806613 1.48042312383933
1 SMI_returnMatrix.out 0.23380724912464781 1.366682496474282
3 TA 35_returnMatrix.out 0.32527237020342453 1.9365870957858298
2 Tadawul All Share_returnMatrix.out 0.249004367198583 1.437914519723979
805 Taiwan Weighted_returnMatrix.out 0.13459108693130886 1.0756326977637694
956 Tanzania All Share_returnMatrix.out 0.36127595979159816 1.6202520769522148
1 Tunindex_returnMatrix.out 0.3442864069815674 1.752304422323601
953 Uganda All Share_returnMatrix.out 0.348065229131443 1.5744149348887138
1 US SmallCap 2000_returnMatrix.out 0.65038728239997 2.0403894279521073
798 WIG_returnMatrix.out 0.14834405533510098 1.0605849629821043
956 Zimbabwe Industrial_returnMatrix.out 0.6487361949889778 1.231096616966227

In [30]:
stdAvg_df = pd.DataFrame(stdAvg_dictList)
stdAvg_df

                                         Name       Std      Mean
0                ADX General_returnMatrix.out  0.381576  1.464753
1                        AEX_returnMatrix.out  0.345527  1.548563
2                    Al-Quds_returnMatrix.out  0.081602  1.204216
3           Amman SE General_returnMatrix.out  0.080319  0.779785
4   Athens General Composite_returnMatrix.out  0.197164  0.719325
..                                        ...       ...       ...
84                  Tunindex_returnMatrix.out  0.344286  1.752304
85          Uganda All Share_returnMatrix.out  0.348065  1.574415
86          US SmallCap 2000_returnMatrix.out  0.650387  2.040389
87                       WIG_returnMatrix.out  0.148344  1.060585
88       Zimbabwe Industrial_returnMatrix.out  0.648736  1.231097

[89 rows x 3 columns]

In [31]:
stdAvg_df.sort_values(['Std', 'Mean'], ascending=[False, False])
# We Delete Bursatil in further study
# Saved in Index-v4-2009&1990.csv

                                             Name         Std        Mean
17                      Bursatil_returnMatrix.out  717.334825  281.619007
70                    S&P Merval_returnMatrix.out    8.251036    8.771887
43                   Karachi 100_returnMatrix.out    2.346136    4.369095
52                    Nasdaq 100_returnMatrix.out    1.333609    2.929792
42                    JSE Market_returnMatrix.out    1.271813    2.750366
..                                            ...         ...         ...
2                        Al-Quds_returnMatrix.out    0.081602    1.204216
3               Amman SE General_returnMatrix.out    0.080319    0.779785
65                            PX_returnMatrix.out    0.077014    1.107073
33  FTSE Straits Times Singapore_returnMatrix.out    0.074181    1.018112
49                         MONEX_returnMatrix.out    0.042600    1.033645

[89 rows x 3 columns]

upperLeftMatrix = np.delete(upperLeftMatrix, 17, 0)

In [44]:
pickle.dump(upperLeftMatrix, open("./output/matrix/upperleft.out", "wb"), protocol=4)

In [37]:
stdAvg_dictList = []
for j, tmpMatrix in enumerate(upperLeftMatrix):
    std = np.nanstd(tmpMatrix[0])
    mean = np.nanmean(tmpMatrix[0])
    i = 0
    while np.isnan(std) or np.isnan(mean):
        i+=1
        std = np.nanstd(tmpMatrix[i])
        mean = np.nanmean(tmpMatrix[i])
    stdAvg_dictList.append({"Name": fileLists[j], "Std": std, "Mean": mean})
    print(i, fileLists[j], std, mean)

/Users/lzcai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.
/Users/lzcai/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: RuntimeWarning: Mean of empty slice
  if __name__ == '__main__':

4 ADX General_returnMatrix.out 0.38157628848175945 1.4647527633366382
1 AEX_returnMatrix.out 0.3455271455795936 1.5485632509052007
3 Al-Quds_returnMatrix.out 0.08160189146649238 1.2042161893463146
3 Amman SE General_returnMatrix.out 0.0803185700810113 0.7797850493289584
1747 Athens General Composite_returnMatrix.out 0.19716420623779243 0.7193252150707149
2272 ATX_returnMatrix.out 0.18656998228241223 1.1103342760183479
508 Bahrain All Share_returnMatrix.out 0.08291796346722446 0.8610306424251024
1 BEL 20_returnMatrix.out 0.3252116517737082 1.5094340810546805
1453 Belex 15_returnMatrix.out 0.1510406090285203 1.2718487306448272
1453 BIRS_returnMatrix.out 0.10726466476195551 0.777245791955044
1 BIST 100_returnMatrix.out 0.723249490696876 2.7157276313027863
4 Blue-Chip SBITOP_returnMatrix.out 0.14888585949651353 0.9047527589768981
1 Bovespa_returnMatrix.out 0.2691153210521693 1.4874955103273626
1888 BRVM Composite_returnMatrix.out 0.14392150620071592 1.0562207501504408
4 BSE Domestic Company_returnMatrix.out 0.17917161586091296 1.192451795428797
957 BSE SOFIX_returnMatrix.out 0.32071793266343995 1.3154477573015633
795 Budapest SE_returnMatrix.out 0.3399282744342838 1.0734055090080856
1 CAC 40_returnMatrix.out 0.21823745743320608 1.25450853637762
1 Costa Rica Indice Accionario_returnMatrix.out 0.5261889963759432 1.3195646332303148
4 CROBEX_returnMatrix.out 0.09788130140707087 1.0484652315586314
1 CSE All-Share_returnMatrix.out 0.889279594250744 3.7026411488714834
953 Cyprus Main Market_returnMatrix.out 0.17878490227531763 0.19818705250604285
1 DAX_returnMatrix.out 0.5150314772940919 1.7731100201553334
1490 Dhaka Stock Exchange 30_returnMatrix.out 0.15839500620773025 1.2132707378616252
1 Dow Jones Industrial Average_returnMatrix.out 0.5344064178794651 1.7550099400717893
957 Ecuador Reinvestment_returnMatrix.out 0.14235302218424778 1.2322319290216164
3 EGX 30_returnMatrix.out 0.7474054232069913 1.729989588387498
1 FTSE 100_returnMatrix.out 0.194001842496183 1.3684626461067781
1 FTSE Colombia_returnMatrix.out 0.2866170263498046 1.7890269750302097
504 FTSE Malaysia KLCI_returnMatrix.out 0.1023511358265203 1.2888933648721836
1 FTSE MIB_returnMatrix.out 0.13927286948533424 0.9759459237822822
1747 FTSE NSX Overall_returnMatrix.out 0.13399842224862557 1.12293663108363
795 FTSE Straits Times Singapore_returnMatrix.out 0.07418110242333999 1.0181119520796016
1 FTSE_JSE Top 40_returnMatrix.out 0.5146464575082448 1.9125829289306144
1 Hang Seng_returnMatrix.out 0.23171666059019658 1.5154295122722177
2133 HNX 30_returnMatrix.out 0.17291606305464627 0.982929085915698
1 IBEX 35_returnMatrix.out 0.12716829264380106 1.0115230456191993
1 ICEX Main_returnMatrix.out 0.5482224298715854 1.531796005647545
1030 ISEQ Overall_returnMatrix.out 0.49729664600562085 1.9369928665235017
1903 ISX Main 60_returnMatrix.out 0.1829963999811043 0.7316908003895851
4 Jakarta Stock Exchange Composite Index_returnMatrix.out 0.8399639107526573 3.0692309106906146
2042 JSE Market_returnMatrix.out 1.271813456346914 2.7503655210270352
1 Karachi 100_returnMatrix.out 2.3461358566221415 4.369094784655774
2063 KASE_returnMatrix.out 0.4544022150075182 1.146020766304272
1 Kenya NSE 20_returnMatrix.out 0.20229246879629487 1.1031110951299072
1 KOSPI_returnMatrix.out 0.23240722277707337 1.6985941959503075
1285 LSE All Share_returnMatrix.out 0.19660997201682923 1.3070492678740004
10 MOEX Russia_returnMatrix.out 0.5845490624732509 2.5778740373727
2723 MONEX_returnMatrix.out 0.042599589121597926 1.0336449782495578
1 Moroccan All Shares_returnMatrix.out 0.1187313228921973 1.0100278825521984
3 MSM 30_returnMatrix.out 0.12720095830679454 1.0346092202084751
1 Nasdaq 100_returnMatrix.out 1.3336086226183845 2.929792365971024
1 NASDAQ Composite_returnMatrix.out 1.0540129973741228 2.532587314268737
1 Nifty 50_returnMatrix.out 0.6853746665214935 2.3055348082518186
4 Nikkei 225_returnMatrix.out 0.536339695472714 1.616947857696888
1124 NSE All Share_returnMatrix.out 0.30139057439135813 1.5556796089782847
4 NZX 50_returnMatrix.out 0.7119048292665912 1.8899937601782555
1 OMX Copenhagen 20_returnMatrix.out 1.003282972449342 2.561228689127295
1 OMX Helsinki 25_returnMatrix.out 0.5000995367473339 1.782629974451604
1 OMX Stockholm 30_returnMatrix.out 0.3871114338982037 1.8253637180412643
1062 Oslo All Share_returnMatrix.out 0.38277383349092753 1.6143802730377272
7 PFTS_returnMatrix.out 0.7249438292358398 1.504020902807947
1036 PHS All Shares_returnMatrix.out 0.16651456002796852 1.4186481099278538
509 PSI 20_returnMatrix.out 0.14428538983138722 0.8716957479023456
1111 PX_returnMatrix.out 0.07701438593114333 1.107073101070333
3 QE General_returnMatrix.out 0.2737305104674865 1.343755675066125
1 S&P 500_returnMatrix.out 0.6066708179766601 1.8950046297386363
1 S&P CLX IPSA_returnMatrix.out 0.279860718340263 1.7280562979490959
956 S&P Lima General_returnMatrix.out 0.16970169132426421 0.8417509815356057
1 S&P Merval_returnMatrix.out 8.251036355544429 8.771886878741448
1 S&P Midcap 400_returnMatrix.out 0.7515410540093175 2.264816704992138
1 S&P_ASX 200_returnMatrix.out 0.1792023238630648 1.3632162344533363
1 S&P_BMV IPC_returnMatrix.out 0.3085703260424114 1.740113383131994
1 S&P_TSX Composite_returnMatrix.out 0.19416787784687514 1.45489365820311
956 SAX_returnMatrix.out 0.2542115559401899 1.1393053374649795
4 Semdex_returnMatrix.out 0.2151423945084919 1.60157678150957
4 SET Index_returnMatrix.out 0.7353997597986501 2.6791907233847567
4 Shanghai Composite_returnMatrix.out 0.2891528666806613 1.48042312383933
1 SMI_returnMatrix.out 0.23380724912464781 1.366682496474282
3 TA 35_returnMatrix.out 0.32527237020342453 1.9365870957858298
2 Tadawul All Share_returnMatrix.out 0.249004367198583 1.437914519723979
805 Taiwan Weighted_returnMatrix.out 0.13459108693130886 1.0756326977637694
956 Tanzania All Share_returnMatrix.out 0.36127595979159816 1.6202520769522148
1 Tunindex_returnMatrix.out 0.3442864069815674 1.752304422323601
953 Uganda All Share_returnMatrix.out 0.348065229131443 1.5744149348887138
1 US SmallCap 2000_returnMatrix.out 0.65038728239997 2.0403894279521073
798 WIG_returnMatrix.out 0.14834405533510098 1.0605849629821043
956 Zimbabwe Industrial_returnMatrix.out 0.6487361949889778 1.231096616966227

In [38]:
stdAvg_df = pd.DataFrame(stdAvg_dictList)
stdAvg_df

                                         Name       Std      Mean
0                ADX General_returnMatrix.out  0.381576  1.464753
1                        AEX_returnMatrix.out  0.345527  1.548563
2                    Al-Quds_returnMatrix.out  0.081602  1.204216
3           Amman SE General_returnMatrix.out  0.080319  0.779785
4   Athens General Composite_returnMatrix.out  0.197164  0.719325
..                                        ...       ...       ...
83                  Tunindex_returnMatrix.out  0.344286  1.752304
84          Uganda All Share_returnMatrix.out  0.348065  1.574415
85          US SmallCap 2000_returnMatrix.out  0.650387  2.040389
86                       WIG_returnMatrix.out  0.148344  1.060585
87       Zimbabwe Industrial_returnMatrix.out  0.648736  1.231097

[88 rows x 3 columns]

In [39]:
stdAvg_df.sort_values(['Std', 'Mean'], ascending=[False, False])

                                             Name       Std      Mean
69                    S&P Merval_returnMatrix.out  8.251036  8.771887
42                   Karachi 100_returnMatrix.out  2.346136  4.369095
51                    Nasdaq 100_returnMatrix.out  1.333609  2.929792
41                    JSE Market_returnMatrix.out  1.271813  2.750366
52              NASDAQ Composite_returnMatrix.out  1.054013  2.532587
..                                            ...       ...       ...
2                        Al-Quds_returnMatrix.out  0.081602  1.204216
3               Amman SE General_returnMatrix.out  0.080319  0.779785
64                            PX_returnMatrix.out  0.077014  1.107073
32  FTSE Straits Times Singapore_returnMatrix.out  0.074181  1.018112
48                         MONEX_returnMatrix.out  0.042600  1.033645

[88 rows x 3 columns]

In [40]:
stdAvg_df.sort_values(['Mean', 'Std'], ascending=[False, False])

                                                 Name       Std      Mean
69                        S&P Merval_returnMatrix.out  8.251036  8.771887
42                       Karachi 100_returnMatrix.out  2.346136  4.369095
20                     CSE All-Share_returnMatrix.out  0.889280  3.702641
40  Jakarta Stock Exchange Composite Index_returnM...  0.839964  3.069231
51                        Nasdaq 100_returnMatrix.out  1.333609  2.929792
..                                                ...       ...       ...
3                   Amman SE General_returnMatrix.out  0.080319  0.779785
9                               BIRS_returnMatrix.out  0.107265  0.777246
39                       ISX Main 60_returnMatrix.out  0.182996  0.731691
4           Athens General Composite_returnMatrix.out  0.197164  0.719325
21                Cyprus Main Market_returnMatrix.out  0.178785  0.198187

[88 rows x 3 columns]

In [42]:
stdAvg_df[stdAvg_df['Mean']>1].sort_values(['Mean', 'Std'], ascending=[False, False])

                                                 Name       Std      Mean
69                        S&P Merval_returnMatrix.out  8.251036  8.771887
42                       Karachi 100_returnMatrix.out  2.346136  4.369095
20                     CSE All-Share_returnMatrix.out  0.889280  3.702641
40  Jakarta Stock Exchange Composite Index_returnM...  0.839964  3.069231
51                        Nasdaq 100_returnMatrix.out  1.333609  2.929792
..                                                ...       ...       ...
50                            MSM 30_returnMatrix.out  0.127201  1.034609
48                             MONEX_returnMatrix.out  0.042600  1.033645
32      FTSE Straits Times Singapore_returnMatrix.out  0.074181  1.018112
36                           IBEX 35_returnMatrix.out  0.127168  1.011523
49               Moroccan All Shares_returnMatrix.out  0.118731  1.010028

[77 rows x 3 columns]