In [1]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv("^GSPC.csv")

In [19]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,1990-01-02,353.399994,359.690002,351.980011,359.690002,359.690002,162070000
1,1990-01-03,359.690002,360.589996,357.890015,358.760010,358.760010,192330000
2,1990-01-04,358.760010,358.760010,352.890015,355.670013,355.670013,177000000
3,1990-01-05,355.670013,355.670013,351.350006,352.200012,352.200012,158530000
4,1990-01-08,352.200012,354.239990,350.540009,353.790009,353.790009,140110000
...,...,...,...,...,...,...,...
7553,2019-12-23,3226.050049,3227.780029,3222.300049,3224.010010,3224.010010,3060610000
7554,2019-12-24,3225.449951,3226.429932,3220.510010,3223.379883,3223.379883,1296540000
7555,2019-12-26,3227.199951,3240.080078,3227.199951,3239.909912,3239.909912,2160680000
7556,2019-12-27,3247.229980,3247.929932,3234.370117,3240.020020,3240.020020,2428670000
7557,2019-12-30,3240.090088,3240.919922,3216.570068,3221.290039,3221.290039,3013290000

In [20]:
type(df['Date'][0])

str

In [21]:
df.drop("Close", axis=1, inplace=True)
df.columns = ["Date", "Open", "High", "Low", "Price", "Vol"]
df['Date'] = pd.to_datetime(df['Date'])
df['Change'] = df['Price'].pct_change()

In [22]:
df

,Date,Open,High,Low,Price,Vol,Change
0,1990-01-02,353.399994,359.690002,351.980011,359.690002,162070000,NaN
1,1990-01-03,359.690002,360.589996,357.890015,358.760010,192330000,-0.002586
2,1990-01-04,358.760010,358.760010,352.890015,355.670013,177000000,-0.008613
3,1990-01-05,355.670013,355.670013,351.350006,352.200012,158530000,-0.009756
4,1990-01-08,352.200012,354.239990,350.540009,353.790009,140110000,0.004514
...,...,...,...,...,...,...,...
7553,2019-12-23,3226.050049,3227.780029,3222.300049,3224.010010,3060610000,0.000866
7554,2019-12-24,3225.449951,3226.429932,3220.510010,3223.379883,1296540000,-0.000195
7555,2019-12-26,3227.199951,3240.080078,3227.199951,3239.909912,2160680000,0.005128
7556,2019-12-27,3247.229980,3247.929932,3234.370117,3240.020020,2428670000,0.000034
7557,2019-12-30,3240.090088,3240.919922,3216.570068,3221.290039,3013290000,-0.005781

In [31]:
df[(df['Date'] > '2013-01-01') & (df['Date'] < '2013-02-01')]

,Date,Open,High,Low,Price,Vol,Change
5797,2013-01-02,1426.189941,1462.430054,1426.189941,1462.420044,4202600000,0.025403
5798,2013-01-03,1462.420044,1465.469971,1455.530029,1459.369995,3829730000,-0.002086
5799,2013-01-04,1459.369995,1467.939941,1458.989990,1466.469971,3424290000,0.004865
5800,2013-01-07,1466.469971,1466.469971,1456.619995,1461.890015,3304970000,-0.003123
5801,2013-01-08,1461.890015,1461.890015,1451.640015,1457.150024,3601600000,-0.003242
5802,2013-01-09,1457.150024,1464.729980,1457.150024,1461.020020,3674390000,0.002656
5803,2013-01-10,1461.020020,1472.300049,1461.020020,1472.119995,4081840000,0.007597
5804,2013-01-11,1472.119995,1472.750000,1467.579956,1472.050049,3340650000,-0.000048
5805,2013-01-14,1472.050049,1472.050049,1465.689941,1470.680054,3003010000,-0.000931
5806,2013-01-15,1470.670044,1473.310059,1463.760010,1472.339966,3135350000,0.001129
5807,2013-01-16,1472.329956,1473.959961,1467.599976,1472.630005,3384080000,0.000197
5808,2013-01-17,1472.630005,1485.160034,1472.630005,1480.939941,3706710000,0.005643
5809,2013-01-18,1480.949951,1485.979980,1475.810059,1485.979980,3795740000,0.003403
5810,2013-01-22,1485.979980,1492.560059,1481.160034,1492.560059,3570950000,0.004428
5811,2013-01-23,1492.560059,1496.130005,1489.900024,1494.810059,3552010000,0.001507
5812,2013-01-24,1494.810059,1502.270020,1489.459961,1494.819946,3699430000,0.000007
5813,2013-01-25,1494.819946,1503.260010,1494.819946,1502.959961,3476290000,0.005445
5814,2013-01-28,1502.959961,1503.229980,1496.329956,1500.180054,3388540000,-0.001850
5815,2013-01-29,1500.180054,1509.349976,1498.089966,1507.839966,3949640000,0.005106
5816,2013-01-30,1507.839966,1509.939941,1500.109985,1501.959961,3726810000,-0.003900
5817,2013-01-31,1501.959961,1504.189941,1496.760010,1498.109985,3999880000,-0.002563

In [29]:
df['Date'].min()+pd.Timedelta(days=10*365)

Timestamp('1999-12-31 00:00:00')

In [36]:
import pickle
result = pickle.load(open("./from github/Stock-Trading-Environment/output/5/sp500_split_04FEB2020.out", "rb"))

In [38]:
len(result)

52

In [39]:
result

[{'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -341.148284985557,
  'max': 204.10823480945146,
  'min': -844.987127308319,
  'std': 281.52406944928754,
  'final': -515.2573594985279,
  'total_shares_sold': 19},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -147.2296701051603,
  'max': 205.22595969825488,
  'min': -778.346796936692,
  'std': 88.63078171196895,
  'final': -86.17203741834965,
  'total_shares_sold': 8},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 161.48114773382525,
  'max': 2570.2803386680516,
  'min': -1100.7808594554426,
  'std': 903.9498464416324,
  'final': -809.2102152846983,
  'total_shares_sold': 4},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 29.707011871318723,
  'max': 523.067753243784,
  'min': -14.92717778113365,
  'std': 110.68678022465276,
  'final': 508.7751880034375,
  'total_shares_sold': 8},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 670.9899978081318,
  'max': 1180.84694132794,
  'min': -84.76419841508505,
  'std': 293.29819686398014,
  'final': 608.4756505055466,
  'total_shares_sold': 87},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -3.8061225157594722,
  'max': 233.84132183846486,
  'min': -683.0901197745807,
  'std': 101.49937915318331,
  'final': 233.84132183846486,
  'total_shares_sold': 7},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 255.03261837448179,
  'max': 632.9048539157338,
  'min': -113.37589564838709,
  'std': 132.0211503871681,
  'final': 343.47775655061923,
  'total_shares_sold': 10},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 315.1091901572937,
  'max': 1566.9920713406937,
  'min': -372.0225628473072,
  'std': 273.18756776874073,
  'final': 1414.856832526415,
  'total_shares_sold': 4},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 256.919611169606,
  'max': 469.35770591681285,
  'min': 0.0,
  'std': 216.28450482547322,
  'final': 420.18914824962485,
  'total_shares_sold': 3},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 42.56708219881238,
  'max': 97.37735763630917,
  'min': -239.53786905460584,
  'std': 47.02443608015056,
  'final': 71.47264539848948,
  'total_shares_sold': 8},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -820.4543458803876,
  'max': 0.0,
  'min': -1505.8146462803288,
  'std': 430.18150772257036,
  'final': -1130.1083148871858,
  'total_shares_sold': 72},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 68.89262154546019,
  'max': 692.9394066339264,
  'min': -183.87893802543113,
  'std': 180.18940556924116,
  'final': 665.6984054830173,
  'total_shares_sold': 6},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 255.87752061184338,
  'max': 2745.7597296938857,
  'min': -1.5248626443735702,
  'std': 630.4160552346453,
  'final': 2553.854076679152,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 106.84530076543143,
  'max': 1565.0224305148404,
  'min': -688.4778069498716,
  'std': 309.64476629427844,
  'final': 1419.5490104237942,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 285.76240311778395,
  'max': 600.3405183034065,
  'min': -309.97288387593653,
  'std': 282.7172521868031,
  'final': 564.8865264636552,
  'total_shares_sold': 3},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -281.2868942343256,
  'max': 1082.1258264375901,
  'min': -1681.8854330315953,
  'std': 662.4143774386376,
  'final': -906.382715039379,
  'total_shares_sold': 3},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 848.9276720546311,
  'max': 1587.3040627510163,
  'min': -255.74369580543134,
  'std': 693.4996931172768,
  'final': 1321.3825645985216,
  'total_shares_sold': 36},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 3.1968064702732506,
  'max': 81.38321910953528,
  'min': -158.36762242996156,
  'std': 18.599184512124914,
  'final': 70.8750313727287,
  'total_shares_sold': 2},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 425.8218428933961,
  'max': 800.9561228407765,
  'min': -227.83496863594155,
  'std': 226.89770806615203,
  'final': 763.5306626405854,
  'total_shares_sold': 10},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 164.60201399605705,
  'max': 339.90599436097,
  'min': -836.7319178310681,
  'std': 242.5462962863974,
  'final': 339.90599436097,
  'total_shares_sold': 7},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 339.80195710707005,
  'max': 601.3389705821173,
  'min': 0.0,
  'std': 246.38288443676865,
  'final': 549.2280443781292,
  'total_shares_sold': 1},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -781.4496212206662,
  'max': 909.0422119741816,
  'min': -3109.843511762743,
  'std': 1194.54479151247,
  'final': -2304.0436009973982,
  'total_shares_sold': 4},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 254.36046506912672,
  'max': 606.588612204996,
  'min': -1.7502880782940338,
  'std': 213.77097561680898,
  'final': 443.68676272938865,
  'total_shares_sold': 2},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 152.02506644435425,
  'max': 237.42325569864443,
  'min': -242.34294835451874,
  'std': 108.17709280972664,
  'final': 217.13908595598878,
  'total_shares_sold': 2},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 885.1986412239329,
  'max': 1536.131027535539,
  'min': -296.5884741572663,
  'std': 428.4015126614243,
  'final': 1084.6262660274078,
  'total_shares_sold': 3},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 288.28258949896446,
  'max': 374.45070577853767,
  'min': -363.90273544934826,
  'std': 153.80559841351678,
  'final': 374.06270982204114,
  'total_shares_sold': 4},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -569.5559976455525,
  'max': 0.0,
  'min': -918.7527138254154,
  'std': 180.3391931392983,
  'final': -672.6402890530007,
  'total_shares_sold': 10},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 14.010350412450729,
  'max': 445.1542128061883,
  'min': -154.62301605220273,
  'std': 67.36297880534632,
  'final': 387.97723552500247,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': -257.39125310080277,
  'max': 262.90574032989025,
  'min': -585.4385657195307,
  'std': 115.75676942154811,
  'final': -291.66870456882316,
  'total_shares_sold': 7},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 65.91706059771572,
  'max': 387.4629057717284,
  'min': -149.29594361716772,
  'std': 148.2702120245784,
  'final': 292.0605790604477,
  'total_shares_sold': 17},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0},
 {'trainStart': Timestamp('1990-01-02 00:00:00'),
  'trainEnd': Timestamp('1999-12-31 00:00:00'),
  'testStart': Timestamp('2014-12-31 00:00:00'),
  'testEnd': Timestamp('2019-12-30 00:00:00'),
  'train_step': 50000,
  'mean': 0.0,
  'max': 0.0,
  'min': 0.0,
  'std': 0.0,
  'final': 0.0,
  'total_shares_sold': 0}]